apiVersion: v1
kind: Service
metadata:
  name: energy-python-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: energy-python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-python
  template:
    metadata:
      labels:
        app: energy-python
    spec:
      containers:
      - name: energy-python
        image: flokisecurity/energy-python-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: python-db-secret
              key: database-url
